// Compiled by ClojureScript 1.9.854 {:static-fns true, :optimize-constants true, :elide-asserts true}
goog.provide('realworld.ui.pages.login');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('keechma.ui_component');
goog.require('keechma.toolbox.ui');
goog.require('keechma.toolbox.forms.helpers');
goog.require('keechma.toolbox.forms.core');
goog.require('realworld.ui.components.pure.form_inputs');
goog.require('realworld.ui.components.pure.form_api_errors');
realworld.ui.pages.login.render = (function realworld$ui$pages$login$render(ctx){
var form_id = new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$login,cljs.core.cst$kw$form], null);
var form_state = cljs.core.deref(keechma.toolbox.forms.helpers.form_state(ctx,form_id));
var helpers = keechma.toolbox.forms.helpers.make_component_helpers(ctx,form_id);
return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$auth_DASH_page_GT_div$container$page_GT_div$row_GT_div$col_DASH_md_DASH_6$offset_DASH_md_DASH_3$col_DASH_xs_DASH_12,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h1$text_DASH_xs_DASH_center,"Sign in"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$p$text_DASH_xs_DASH_center,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$a,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$href,keechma.ui_component.url(ctx,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$page,"register"], null))], null),"Need an account?"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [realworld.ui.components.pure.form_api_errors.render,form_state], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$form,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$on_DASH_submit,cljs.core.cst$kw$submit.cljs$core$IFn$_invoke$arity$1(helpers)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [realworld.ui.components.pure.form_inputs.controlled_input,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.cst$kw$form_DASH_state,form_state,cljs.core.cst$kw$helpers,helpers,cljs.core.cst$kw$placeholder,"Email",cljs.core.cst$kw$attr,cljs.core.cst$kw$email], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [realworld.ui.components.pure.form_inputs.controlled_input,new cljs.core.PersistentArrayMap(null, 5, [cljs.core.cst$kw$form_DASH_state,form_state,cljs.core.cst$kw$helpers,helpers,cljs.core.cst$kw$placeholder,"Password",cljs.core.cst$kw$attr,cljs.core.cst$kw$password,cljs.core.cst$kw$input_DASH_type,cljs.core.cst$kw$password], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$button$btn$btn_DASH_lg$btn_DASH_primary$pull_DASH_xs_DASH_right,"Sign in"], null)], null)], null);
});
realworld.ui.pages.login.component = keechma.ui_component.constructor$(new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$renderer,realworld.ui.pages.login.render,cljs.core.cst$kw$topic,keechma.toolbox.forms.core.id_key,cljs.core.cst$kw$subscription_DASH_deps,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$form_DASH_state], null)], null));
