// Compiled by ClojureScript 1.9.229 {:static-fns true, :optimize-constants true, :elide-asserts true}
goog.provide('realworld.ui.pages.profile');
goog.require('cljs.core');
goog.require('keechma.ui_component');
goog.require('keechma.toolbox.ui');
goog.require('keechma.toolbox.util');
realworld.ui.pages.profile.render_tabs = (function realworld$ui$pages$profile$render_tabs(ctx){
var current_route = keechma.toolbox.ui.route_GT_(ctx);
var favorites_QMARK_ = cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2("favorites",cljs.core.cst$kw$detail.cljs$core$IFn$_invoke$arity$1(current_route));
var user = keechma.toolbox.ui.sub_GT_(ctx,cljs.core.cst$kw$profile_DASH_user);
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$articles_DASH_toggle_GT_ul$nav$nav_DASH_pills$outline_DASH_active,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$li$nav_DASH_item,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$a$nav_DASH_link,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$href,keechma.ui_component.url(ctx,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$page,"profile",cljs.core.cst$kw$subpage,cljs.core.cst$kw$username.cljs$core$IFn$_invoke$arity$1(user)], null)),cljs.core.cst$kw$class,keechma.toolbox.util.class_names(new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$active,!(favorites_QMARK_)], null))], null),"My Articles"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$li$nav_DASH_item,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$a$nav_DASH_link,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$href,keechma.ui_component.url(ctx,new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$page,"profile",cljs.core.cst$kw$subpage,cljs.core.cst$kw$username.cljs$core$IFn$_invoke$arity$1(user),cljs.core.cst$kw$detail,"favorites"], null)),cljs.core.cst$kw$class,keechma.toolbox.util.class_names(new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$active,favorites_QMARK_], null))], null),"Favorited Articles"], null)], null)], null);
});
realworld.ui.pages.profile.render = (function realworld$ui$pages$profile$render(ctx){
var user = keechma.toolbox.ui.sub_GT_(ctx,cljs.core.cst$kw$profile_DASH_user);
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$profile_DASH_page,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$user_DASH_info_GT_div$container_GT_div$row_GT_div$col_DASH_xs_DASH_12$col_DASH_md_DASH_10$offset_DASH_md_DASH_1,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$img$user_DASH_img,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$src,cljs.core.cst$kw$image.cljs$core$IFn$_invoke$arity$1(user)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h4,cljs.core.cst$kw$username.cljs$core$IFn$_invoke$arity$1(user)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$p,cljs.core.cst$kw$bio.cljs$core$IFn$_invoke$arity$1(user)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$pull_DASH_xs_DASH_right,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [keechma.ui_component.component(ctx,cljs.core.cst$kw$follow_DASH_button),user], null)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$container_GT_div$row_GT_div$col_DASH_xs_DASH_12$col_DASH_md_DASH_10$offset_DASH_md_DASH_1,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [realworld.ui.pages.profile.render_tabs,ctx], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [keechma.ui_component.component(ctx,cljs.core.cst$kw$articles)], null)], null)], null);
});
realworld.ui.pages.profile.component = keechma.ui_component.constructor$(new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$renderer,realworld.ui.pages.profile.render,cljs.core.cst$kw$component_DASH_deps,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$articles,cljs.core.cst$kw$follow_DASH_button], null),cljs.core.cst$kw$subscription_DASH_deps,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$profile_DASH_user,cljs.core.cst$kw$current_DASH_user], null)], null));
